#beep  
print("        O         ")
print("        |         ")
print("        |         ")
print("    #########     ")
print("    # 0   0 #     ")
print("    #  [_]  #     ")
print("    ##########    ")
print("        ||        ")
print("##################")
print("# ##          ## #")
print("# ##          ## #")
print("# ##          ## #")
print("##################")
print("    ##########    ")
print("    ##########     ")
print("    #   ##   #     ")
print("    #   ##   #     ")
print("    #   ##   #     ")
print("    ##########    ")

#read input s
print("What symbol what you like for the robots eyes?")
eyes = input()

print("        O         ")
print("        |         ")
print("        |         ")
print("    #########     ")
print("    # ",(eyes),   (eyes)," #     ")
print("    #  [_]  #     ")
print("    ##########    ")
print("        ||        ")
print("##################")
print("# ##          ## #")
print("# ##          ## #")
print("# ##          ## #")
print("##################")
print("    ##########    ")
print("    ##########     ")
print("    #   ##   #     ")
print("    #   ##   #     ")
print("    #   ##   #     ")
print("    ##########    ")